### ISSUE TITLE
Apache behind NGINX reverse proxy with mod_aclr2 & mod_rpaf / mod_remoteip

### ISSUE THREAD

**Issue by robots4life** [bitnami/bitnami-docker-apache#100]
The [bitnami-docker-apache image](https://github.com/bitnami/bitnami-docker-apache) works great. Thank you for your work on this. :heart: 

I am using the [linuxserver/docker-letsencrypt image](https://github.com/linuxserver/docker-letsencrypt) to automatically get certs, that image comes with NGINX. Went on and configured NGINX as reverse proxy for Apache, enabled SSL and made sure to [secure HTTP traffic to upstream servers](https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/) like Apache, in this case. Works **fine** so far. Example files below.

Now I read [https://docs.plesk.com/en-US/obsidian/administrator-guide/web-servers/apache-and-nginx-web-servers-linux/apache-with-nginx.70837/](https://docs.plesk.com/en-US/obsidian/administrator-guide/web-servers/apache-and-nginx-web-servers-linux/apache-with-nginx.70837/) and would like to implement that procedure.

For that to work I need the [mod_aclr2](https://github.com/defanator/mod_aclr2) module and the   [mod_remoteip](https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html) module.

I found
`#LoadModule remoteip_module modules/mod_remoteip.so`
in `httpd.conf` and assume I can just remove the comment and that module will work?
If not, how could I get it to work please?

More so, I think I need to extend this [bitnami-docker-apache image](https://github.com/bitnami/bitnami-docker-apache) and include the [mod_aclr2](https://github.com/defanator/mod_aclr2) module into the build process.

Hoping this is _not too much to ask_, any guidance on how to get the [mod_aclr2](https://github.com/defanator/mod_aclr2) module to work in this Apache image would be fantastic. :kiss:

---
**Apache behind NGINX reverse proxy**
Here is a little info for anyone interested to automatically get SSL certs for your domain and all sudomains and how to have Linuxserver Letsencrypt with NGINX as a reverse proxy for Bitnami Apache.

Below are the `docker-compose.yml`, the `default` config file for NGINX that you will need for the letsencrypt container and the `example.vhost.conf` you will need for your Apache container.

Traffic comes in on 80 is forwarded to 443 by NGINX, then it is forwarded through to an upstream Apache server while accepting incoming request on 8443.

[docker-compose.yml.txt](https://github.com/bitnami/bitnami-docker-apache/files/4499273/docker-compose.yml.txt)
[default.txt](https://github.com/bitnami/bitnami-docker-apache/files/4499276/default.txt)
[example.vhost.conf.txt](https://github.com/bitnami/bitnami-docker-apache/files/4499277/example.vhost.conf.txt)
Just make sure to remove the `.txt` from the file names of course. :roll_eyes: :smile_cat:

**Comment by robots4life** [comment]
Oh wow, I just found [this](https://github.com/bitnami/bitnami-docker-apache/blob/master/2.4/debian-10/rootfs/opt/bitnami/apache/conf/bitnami-templates/bitnami-ssl.conf.tpl) so will go over the example.vhost.conf.txt file and see where what I came up with differs. Great you have that example template there. :+1:

**Comment by robots4life** [comment]
So I managed to add the mod_aclr2 module to a running instance of the Bitnami Apache container like this.
```# sh into running bitnami_apache container as root
# docker exec -it --user root bitnami_apache sh

# to download the the mod_aclr2 module we need wget
# apt update
# apt upgrade
# apt install wget
# wget https://raw.githubusercontent.com/defanator/mod_aclr2/master/mod_aclr2.c

# so now we download the mod_aclr2 module into the corresponding directory
# inside bitnami_apache container at
# /opt/bitnami/apache/modules
# run below command
# wget https://raw.githubusercontent.com/defanator/mod_aclr2/master/mod_aclr2.c

# https://github.com/defanator/mod_aclr2#apache-mod_aclr2-installation-and-configuration
# then we try to compile the module using apxs
# apxs -c mod_aclr2.c

# but get following error
# line 1752: gcc: command not found

# hence let's install gcc ;)
# https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/
# apt install build-essential

# now it works! we can compile the module
# apxs -c mod_aclr2.c

# https://github.com/defanator/mod_aclr2#apache-mod_aclr2-installation-and-configuration
# and then we install and activate the mod_aclr2 module
# apxs -i -a -n aclr mod_aclr2.la

```
The result of the last command could be something like this.
```
# apxs -i -a -n aclr mod_aclr2.la
/opt/bitnami/apache/build/instdso.sh SH_LIBTOOL='/opt/bitnami/apache/build-1/libtool' mod_aclr2.la /opt/bitnami/apache/modules
/opt/bitnami/apache/build-1/libtool --mode=install install mod_aclr2.la /opt/bitnami/apache/modules/
libtool: install: install .libs/mod_aclr2.so /opt/bitnami/apache/modules/mod_aclr2.so
libtool: install: install .libs/mod_aclr2.lai /opt/bitnami/apache/modules/mod_aclr2.la
libtool: install: install .libs/mod_aclr2.a /opt/bitnami/apache/modules/mod_aclr2.a
libtool: install: chmod 644 /opt/bitnami/apache/modules/mod_aclr2.a
libtool: install: ranlib /opt/bitnami/apache/modules/mod_aclr2.a
libtool: finish: PATH="/opt/bitnami/common/bin:/opt/bitnami/common/bin:/opt/bitnami/apache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /opt/bitnami/apache/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /opt/bitnami/apache/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
chmod 755 /opt/bitnami/apache/modules/mod_aclr2.so
[activating module `aclr' in /opt/bitnami/apache/conf/httpd.conf]
```

Once I figure out how to properly use this new module I will report back. :pray:

**Comment by robots4life** [comment]
All of the above adds this line below to `/opt/bitnami/apache/conf/httpd.conf`, the default Apache config in this image. Note we are still in the currently running Bitnami Apache container.

`LoadModule aclr_module        modules/mod_aclr2.so`

So that works. :smiley: 
The thing is, when I stop the container these changes are gone. :crying_cat_face: 
How can I persist those newly installed packages and module in the Bitnami Apache container after it was stopped?

**Comment by robots4life** [comment]
In order to persist the changes and have the aclr2 module installed in the container on startup I am trying to pass the above commands in the docker-compose file. But then I am stuck. :stop_sign:

The Bitnami Apache container exits with code 0.
```
bitnami_apache | apache 20:56:22.31 
bitnami_apache | apache 20:56:22.31 Welcome to the Bitnami apache container
bitnami_apache | apache 20:56:22.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-apache
bitnami_apache | apache 20:56:22.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-apache/issues
bitnami_apache | apache 20:56:22.33 Send us your feedback at containers@bitnami.com
bitnami_apache | apache 20:56:22.33 
bitnami_apache | 
bitnami_apache | Hello World
bitnami_apache exited with code 0
```
The `docker-compose.yml` looks like this.
```
apache:
    image: 'bitnami/apache:latest'
    # https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/
    user: root

    container_name: bitnami_apache

    command: echo 'Hello World'
    # command: "sh -c 'apt-get update && apt-get upgrade && apt-get install wget -y'"
```
Found this issue https://github.com/bitnami/bitnami-docker-phpmyadmin/issues/19#issuecomment-404807814 and had a look at https://github.com/bitnami/bitnami-docker-apache/blob/master/2.4/debian-10/rootfs/opt/bitnami/scripts/apache/entrypoint.sh but am not sure what to put last into the command so that the Bitnami Apache container keeps running.

What would the 

> non-exit command

look like for Bitnami Apache container please?

Any help much appreciated thinking I am close to getting this to work, fingers crossed. :v:

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami :) So, let me see if I understand correctly. You want to have that module enabled and have the configuration persisted between restarts, am I correct? If that's the case you could try mounting your own httpd.conf file in `/opt/bitnami/apache/conf`. This way the information should be persisted. Could you try that?
