### ISSUE TITLE
bitnami for apache on Docker

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-apache#103]
My environment consists of development laptop and a EC2 AWS server. The laptop is running a docker container. In it I run bitnami/Apache and bitnami/php-fpm. This is my entire development environment. I use phpStorm and have a Github setup where I can pushe my changes to Github and these are automatically pushed to my Ec2 instance. My application uses RDS mySQL and S3 and AWS dynamaDB.

I also have a AWS EC2 instance. This is my staging server and I will use this for testing. Thus it is also running the same bitnami/Apache and bitnami/php-fpm (I think).

I am trying to setup to use AWS Secrets Manager. To do this I need to setup a CredentialProvider and the AWS docs say to do this at /home/.aws/configuration. I have run Configure Credentials to create the defaultProvider. This app seems to be creating it in /home/.aws/. But the Bitnami docs say to create it in home/bitnami/.aws/. The issue is that I don's see a /home/bitnami dir in the container. Please advise.

I also am not sure, since I don't see /home/binami/.aws, if I have correctly set up bitnami under docker. How can I check this?

I also need to create an ENV variable called machine. If this is set to LAPTOP, then my code needs to run a slightly different setting for FusionAuth, that I use to enable users to answer surveys. But I can't seem to find .htaccess (either on the laptop or on the server) and this is where I will create the ENV variable.

**Comment by andresbono** [comment]
Hi @richb201, to get more context, can you share the guides that you are following to configure AWS Secrets Manager? Can you also share the Bitnami doc?

You are probably following a guide about EC2 instances, because in general, containers don't include the `/home/bitnami` directory.

**Comment by richb201** [comment]
Thanks for the response. I guess the source of the issue is that I have used Bitnami Apache in the past and was not aware that the docker containers' configuration is different. I am not sure which document to follow now? I found out that I can't log in to my instance via username bitnami. How about all the mods to support security and maint that the non Docker version has? How about the locations of files such as .htaccess. Where are these in the Bitnami apache docker version?

**Comment by richb201** [comment]
One more thing. I am having trouble Putty'ing into the Instance. What is the port used? I know that normally the port number for SSH is 2222 but sometimes that is changed for security purposes. What is it for docker bitnami/apache?

**Comment by andresbono** [comment]
Hi @richb201, container images don't usually create multiple users. Instead, they run with an unprivileged user (with uid `1001`). You can read more on the topic here: https://docs.bitnami.com/tutorials/work-with-non-root-containers/.

In the same line, you don't access to a container with SSH. It is not even installed. Instead, you usually mount the data as a volume where you can do modifications in the host machine: https://docs.docker.com/storage/volumes/.

It is a different approach than working with cloud images. If you prefer, you can always use our AWS AMI for LAMP: https://bitnami.com/stack/lamp/cloud/aws.

**Comment by richb201** [comment]
Andres, the reason I initially contacted bitnami support was that I am trying to setup AWS Secrets Manager and am having issues with accessing the Credential Provider. I am not enough expert on Docker to be able to modify the environment at this late stage in the development. What I liked about bitnami LAMP was the documentation and support. Now, a few years into development it seems that I have lost that by using the Docker version of bitnami apache.

I am willing to try to use image:root as discussed in your attachment or perhaps a better solution is to abandon my attempt to use Secrets Manager and use Docker Secrets instead?

**Comment by richb201** [comment]
Andres, does bitnami offer the same docker images I am using, apache and php-fpm in root versions?

**Comment by richb201** [comment]
I tried modifying the ownership as recommended. Here is part of my compose:
php-fpm:
    container_name: "php"
    build: ./php
    restart: unless-stopped
    image: bitnami/php-fpm
    user: "1001:1001"
    user: "root:root"
    volumes:
      - ./app:/app
    networks:
      - net

When I don't have 1001, I get this error from codeigniter:
A PHP Error was encountered
Severity: Warning

Message: session_start(): Failed to read session data: user (path: /app/application/cache)

Filename: Session/Session.php

Line Number: 143

Backtrace:

File: /app/application/core/MY_Loader.php
Line: 284
Function: library

File: /app/application/controllers/Users.php
Line: 15
Function: __construct

Any idea how to fix this?

**Comment by andresbono** [comment]
Hi @richb201, as you are doing, you can run the containers as root if you specify the `user: root` attribute in the docker-compose.yaml

About the error that you are getting, you might be missing the proper permissions to read `/app/application/cache` or maybe the path doesn't exist. That will depend on the application that you are mounting in the container. You might want to exec into the container to check what is going on:

```
docker-compose exec php-fpm bash
```

**Comment by richb201** [comment]
Thanks Andres. The problem is that my code currently uses this:
php-fpm:
    container_name: "php"
    build: ./php
    restart: unless-stopped
    image: bitnami/php-fpm
    user: "1001:1001"
    volumes:
      - ./app:/app
    networks:
      - net
So the user is being set to 1001. That makes the application run fine. But
if I change it to user:root, the application bombs. Is there a way of
setting user to both root and 1001?

I'd settle for just setting up the AWS secrets in the docker-compose
environment:. Not too secure, right?

**Comment by andresbono** [comment]
I'm not familiar with AWS Secrets Manager, but in general, you may want to install agents in the host machine (the AWS instance) and mount secrets into the container as volumes or by passing environment-variables. Does it make sense? That way, you can continue running your container as an unprivileged user, which is safer.

**Comment by richb201** [comment]
Got it. I thought about passing in the passwords as environment variables.
Is keeping them in docker-compose secure?

**Comment by andresbono** [comment]
If you want to avoid putting them directly in the docker-compose, you can mount the secrets as volumes instead of env-vars, you can use [The “env_file” configuration option](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option) or maybe in your case, you can make use of [Docker secrets](https://www.docker.com/blog/docker-secrets-management/).

**Comment by richb201** [comment]
Thanks Andres. I am already using a .env file. Here is part of my .env file:
TESTHOST=2
and here is part of my docker-compose:
php-fpm:
    container_name: "php"
    build: ./php
    environment:
        TESTHOST: ${TESTHOST}
    restart: unless-stopped
    image: bitnami/php-fpm
    user: "1001:1001"
    volumes:
      - ./app:/app
      - ~/.aws:/root/.aws 
    networks:
      - net

This works and when I run docker exec 98e env I can see the TESTHOST env variable is being set correctly.  But when I run my debugger, I don't see TESTHOST anywhere. Here is the code I am trying to use to see if it worked:

        $testhost=getenv('TESTHOST');
This yields $testhost=null. 

I did find something that said that I will need to  rebuild the image with (I am assuming bitnami/php-fpm) with PassEnv env-variable [env-variable] ... set. The description says: "Specifies one or more native system environment variables to make available as internal environment variables, which are available to Apache HTTP Server modules as well as propagated to CGI scripts and SSI pages. Values come from the native OS environment of the shell which invoked the ..."

But I dont have the knowledge to rebuild the image. That is why I am using Bitnami! 

Any other ideas of how to get the env variable into my application? You can see farther down the docker-compose where I attempted to mount the /root/.aws inorder to get SecretsManagerClient() to work? 

from my code:

SecretsManagerClient([
            'version' => 'latest',
            'region' => 'us-east-1',
        ]);

This doesn't return the secrets, however, 
So I am out of ideas. I am hoping you have a few other things for me to try without rebuilding the image?

**Comment by carrodher** [comment]
I'm sorry but I am not sure how can we help with this issue since, per the above comments,  it seems there is nothing related to the container itself. If you need to perform some customizations to the container image you can take a look at this section in the README https://github.com/bitnami/bitnami-docker-apache#customize-this-image

**Comment by richb201** [comment]
Hi. I have already made some custom mods of the .env file to pass in environment variables. I have stepped back from trying to get CredentialProvider to work and am trying to just pass in my credentials via an .env.  As I said, i can see that they are successfully being passed into the environment. But for some reason I cannot seem to "see them" from my code running in the bitnami/bitnami-docker-apache container. Could it be that the container is using user 1001 and my code is not? Or does that ONLY affect files? 

Regardless I need to understand why my code can't see the env variable that I have passed in. Clearly I am not an expert Docker user. If I was, I probably wouldn't be using bitnami for it. Here is what I see from within the container:
richb201@richb201-XPS-13-9370:~$ docker exec 98e env
PATH=/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=98e2bc145c98
TESTHOST=2
BITNAMI_APP_NAME=php-fpm
BITNAMI_IMAGE_VERSION=7.2.32-debian-10-r1
OS_ARCH=amd64
OS_FLAVOUR=debian-10
OS_NAME=linux
HOME=/home/www

TESTHOST is the sample env that I have passed in. I am trying to see it from my program using:
     $testhost=getenv('TESTHOST');
But instead of getting 2, I get null. Can you think of any way I could debug this problem?

**Comment by richb201** [comment]
In doing some more reading of the article you attached, I see this:
Environment variables
When you start the Apache image, you can adjust the configuration of the instance by passing one or more environment variables either on the docker-compose file or on the docker run command line. If you want to add a new environment variable:

For docker-compose add the variable name and value under the application section:
version: '2'

services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8081'
      - '443:8443'
    environment:
      - APACHE_HTTP_PORT_NUMBER=8081
For manual execution add a -e option with each variable and value:

It is great that you guys included infor on how to pass in an environment variable. But honestly I am confused that the image was built without allowing environment variables. 

**variables_order string**
Sets the order of the EGPCS (Environment, Get, Post, Cookie, and Server) variable parsing. For example, if variables_order is set to "SP" then PHP will create the superglobals $_SERVER and $_POST, but not create $_ENV, $_GET, and $_COOKIE. Setting to "" means no superglobals will be set.

If the deprecated register_globals directive is on, then variables_order also configures the order the ENV, GET, POST, COOKIE and SERVER variables are populated in global scope. So for example if variables_order is set to "EGPCS", register_globals is enabled, and both $_GET['action'] and $_POST['action'] are set, then $action will contain the value of $_POST['action'] as P comes after G in our example directive value.

I have created the env variable fine. But when I try to see it in my script in my app, $_ENV is empty. Now I am thinking that this is because when the image was built, an "E" was not included in the variables_order string?

How, short of rebuilding the image, can I get the $_ENV to populate?

**Comment by andresbono** [comment]
Hi @richb201, the environment variable is being passed to the container, you can see it when you executed the `env` shell command. It should be something that is wrong in the code of your application. We tried the following command that runs php executing a simple echo. It works as expected:

```
$ docker run --rm -it -e TESTHOST=2 bitnami/php-fpm php -r 'echo "The value of the env-var: " . getenv("TESTHOST") . "\n";'
The value of the env-var: 2
```

**Comment by richb201** [comment]
Andres, I hired a consultant who helped me get .env working, so I am ok on this. I have another issue. I am trying to take a file and convert it into a string so that I can assign it to a BLOB in mysql rds. But the php function file_get_contents() is failing. One possibility is that allow_url_fopen is not enabled in php.ini. I actually don't know how to view php_info() in docker. Is there a way to check this (allow_url_fopen) without going crazy? 

Honestly, my docker skills are poor and if i wasn't so close to release, I would just step back from docker completely.

**Comment by andresbono** [comment]
Hi @richb201, you can check that `allow_url_fopen` is activated by executing the following command:

```console
$ docker run --rm -it bitnami/php-fpm bash -c 'php -i | grep allow_url_fopen'
allow_url_fopen => On => On
```

`php -i` is a common way to see PHP information in the command line.

**Comment by richb201** [comment]
Andres, sorry I was responding to Hernandez's response, not yours. Thanks
for the help.
