### ISSUE TITLE
How can we disable SSL?

### ISSUE THREAD

**Issue by encryptblockr** [bitnami/bitnami-docker-apache#107]
Seems the pre-configured SSL is a serious issue with simply/quickly using the docker image 
Can you add a variable to disable SSL and only allow app to listen on 8080???

**Comment by alvneiayu** [comment]
hi @encryptblockr 

I am going to close this issue, we are going to continue the issue in the new one [#103 ](https://github.com/bitnami/bitnami-docker-opencart/issues/103). My colleague @pablogalegoc is answering you.

Thanks a lot

Álvaro
