### ISSUE TITLE
Adding libapache2-svn to image

### ISSUE THREAD

**Issue by burningd0g** [bitnami/bitnami-docker-apache#4]
Hello,

Your apache container works quite well! But it seems to lack libapache2-svn package so it can't be used to server svn repository which would be great as it seems like no working apache docker seems to exist for this purpose.

**Comment by prydonius** [comment]
Hi,

Thank you very much for the suggestion. Unfortunately, in the interest of not bloating this image, we don't plan to support third-party modules.

However, we will consider supporting a separate Subversion server image for Docker.

Thanks,
Adnan
