### ISSUE TITLE
possible to run services as non-root user

### ISSUE THREAD

**Issue by speedupmate** [bitnami/bitnami-docker-apache#5]
is there a guide somewhere how to run bitnami/apache or other services as non-root user inside a container ? 

tried following 

RUN groupadd -r randomgroup && usermod -a -G randomgroup www-data
RUN chown -R www-data:randomgroup /opt/bitnami
USER www-data

but ran to permission issues on running the container 

cp: cannot create directory '/opt/bitnami/apache2/conf/bitnami': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/deflate.conf': Permission denied
cp: cannot create directory '/opt/bitnami/apache2/conf/extra': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/httpd.conf': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/magic': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/mime.types': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/modsecurity.conf': Permission denied
cp: cannot create directory '/opt/bitnami/apache2/conf/original': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/pagespeed.conf': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/pagespeed_libraries.conf': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/privkey.pem': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/server.crt': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/server.csr': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/server.key': Permission denied
cp: cannot create regular file '/opt/bitnami/apache2/conf/ssi.conf': Permission denied
cp: cannot create directory '/opt/bitnami/apache2/conf/vhosts': Permission denied

**Comment by prydonius** [comment]
The apache master process is run as root so that it can bind to port 80, it then spawns unprivileged worker processes (under the 'daemon' user).

If you really don't want the container to start up as root (so that you're also not root when exec'ing in the container), you can make the following changes:

```
FROM bitnami/apache
RUN groupadd -r randomgroup && usermod -a -G randomgroup www-data
RUN echo "www-data ALL=(ALL) NOPASSWD: /bin/chown, /opt/bitnami/apache2/bin/httpd" >> /etc/sudoers
RUN chown -R www-data:randomgroup /opt/bitnami
RUN echo "#!/bin/bash\nsudo chown -R www-data:randomgroup /opt/bitnami\n/entrypoint.sh \"\$@\"" > /perm-fix.sh && chmod +x /perm-fix.sh
USER www-data
ENTRYPOINT ["/perm-fix.sh"]
CMD ["sudo", "httpd", "-DFOREGROUND", "-f", "/opt/bitnami/apache2/conf/httpd.conf"]
```

The **bad** thing about this is that `sudo` will fork to run `httpd`, so apache doesn't become PID 1. Since `sudo` won't forward signals to `httpd`, running `docker stop` or `docker kill` won't gracefully stop the apache process.

**Comment by speedupmate** [comment]
thanks for this info it really helps. i'll explore if i can swap the daemon user and it's group to my needs 

I'm not a sysadmin and maybe I ask things that are obvious but **what if apache would not have to run on 80 and does not need root and we don't need to sudo and gain graceful features back?**

The reason i'm asking is that i tried the bitnami images combo mariadb, redis, phpfpm and apache and ended up in different user permission jungle when volumes are connected or mounted to hosts on top of coreos based cluster. So what i'm after here is to assure (with setup scripts) that all related containers have a common user and group that is not root and is priviledged to read or execute a set of deployed files (like a webapp or logs). I can also arrange that if ever needed to map those volumes to host that the same user with same group and (id -s)  are existing and the same setup could be used for debugging or developing in test environments.

**Comment by prydonius** [comment]
How did you get on @speedupmate?

If your Apache vhosts aren't listening on a privileged port, you don't need to run `httpd` with sudo. The php-fpm container will chown files in /app to bitnami:bitnami, but maybe it makes more sense files were owned by bitnami:daemon, so the apache/nginx containers have proper access to the files. Is this what you're thinking?

**Comment by speedupmate** [comment]
Thanks for getting back I had to delay this but in general 

* yes I'll try to set vhosts to unprivileged ports and just map those with docker cause those ports are never directly revealed so it does not really matter here. 
* yes i'm after that containers have proper access to files and also host has the same bitnami:daemon (or whatever user group) combo with same user and group id in case volumes need to be mapped to the host as it often is with development environments to simplify the flow. 

you can close this ticket but maybe in the future you can make the user:group combo that all your docker  services run as configurable via ENV variables (if it is not jet)
