### ISSUE TITLE
Custom SSL cert steps don't work

### ISSUE THREAD

**Issue by prydonius** [bitnami/bitnami-docker-apache#63]
The custom SSL cert steps don't work because Apache initialisation overwrites the certificates.

https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates

cc @javsalgar

**Comment by dgonzalezruiz** [comment]
Hi @prydonius ,

Thank you for letting us know about this. I've isolated the source of issues. Under the premise that you modified those files before the first initialization ( let me know if that premise is not true in your case ), the first initialization assumed that the volume was clean, and overwrote your copied certificate files with our default, self-signed ones. 

I will be back here with a PR that fixes this as soon as I can. Stay tuned! :)

**Comment by tompizmor** [comment]
This is now fixed in the Apache Docker image.

The README has also been updated: https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates

Tags: `2.4.35-debian-9-r16`, `2.4.35-ol-7-r18`, and `2.4.35-rhel-7-r1`
