### ISSUE TITLE
Unable to install mod_xsendfile

### ISSUE THREAD

**Issue by juban** [bitnami/bitnami-docker-apache#81]
When trying to install mod_xsendfile on top of the container, the `apxs` binary throws an error:

```
curl -O https://tn123.org/mod_xsendfile/mod_xsendfile.c
/opt/bitnami/apache/bin/apxs -cia mod_xsendfile.c
```

Resulting in the following error:
`apxs:Error: /usr/bin/apu-1-config not found!.`

Could not find a way to make it work.

**Comment by juan131** [comment]
Hi @juban 

There are several packages not included in the Bitnami Docker Image for Apache to make it as tiny as possible. Therefore, you need to install them for certain actions such as compiling a C program. Please connect to your container:

```
docker exec -it YOUR_CONTAINER_ID bash
```

And run:

```
install_packages gcc libapr1-dev libaprutil1-dev
```

After that, you should be able to compile the mod_xsendfile by running:

```
apxs -cia mod_xsendfile.c
```

Once it's installed:

```
ls /opt/bitnami/apache/modules/ | grep xsend
mod_xsendfile.so
```

Add the line below to the `/opt/bitnami/apache/conf/httpd.conf` file:

```
LoadModule xsendfile_module   modules/mod_xsendfile.so
```

And restart Apache

```
nami restart apache
```

Check the module is loaded:

```
/opt/bitnami/apache/bin/apachectl -M | grep xsend
 xsendfile_module (shared)
```

**Comment by juban** [comment]
Thank you for help.

Installing the missing libs did the job. 
Maybe some notes about that in the README could be helpful.
In fact, you don't even have to add the LoadModule directive to the https.conf file because apxs will do it for you, just have to restart apache.

Thanks again.
