### ISSUE TITLE
Need to restart apache server, can't locate ctlscript.sh

### ISSUE THREAD

**Issue by joshuadbaker** [bitnami/bitnami-docker-apache#83]
I need to restart apache server. The docs point me to this command:
sudo /opt/bitnami/ctlscript.sh restart apache

When I go into the bash and go into the /opt/bitnami/ directory, the ctlscript.sh isn't there. I looked for it but have not been able to find it anywhere else. I'm using the latest version of the docker image and have found it very useful so far except for this issue. Any thoughts? Thanks!

**Comment by juan131** [comment]
Hi @joshuadbaker 

The **ctlscript.sh** is something we include in the Bitnami stacks but there is not such script on the Bitnami containers. 

In order to restart the Apache server, you need to use **[Nami](https://github.com/bitnami/nami)**. You can easily restart it by running the command:

```
nami restart apache
```

**Comment by dbmedia** [comment]
I tried with the command on the bitnami/laravel docker image but I receive this message:
`nami restart apache`

but I receive this error
`nami ERROR Cannot find any module matching the provided specification 'apache'`

**Comment by juan131** [comment]
The `bitnami/laravel` docker image doesn't include Apache @dbmedia 
It uses the command below to start the web application:

```bash
php artisan serve --host=0.0.0.0 --port=3000
```

You can check it at https://github.com/bitnami/bitnami-docker-laravel/blob/master/5/debian-9/Dockerfile#L22

**Comment by 1si11cs122** [comment]
i tried nami restart apache But get and error  nami: not found

**Comment by juan131** [comment]
@1si11cs122 the Bitnami Apache image is based on bash logic and it doesn't use Nami to configure/initialize Apache since version `2.4.41-debian-9-r40`, see:

- https://github.com/bitnami/bitnami-docker-apache#2441-debian-9-r40-and-2441-ol-7-r42
