### ISSUE TITLE
Expose ports in Docker image has changed in the 2.4.34 release

### ISSUE THREAD

**Issue by myspotontheweb** [bitnami/bitnami-docker-apache#87]
**Description**

The ports exposed by the Docker image in Dockerhub have changed in the "latest" release, 2.4.34

https://hub.docker.com/r/bitnami/apache/

**Steps to reproduce the issue:**

1. [Pull images]

```
docker pull bitnami/apache:latest
docker pull bitnami/apache:2.4.33
docker pull bitnami/apache:2.4.34
```

2. [Run images]

Run the 3 images, mapping the expected port 80.

```
docker run -d -p 8081:80 bitnami/apache:2.4.33
docker run -d -p 8081:80 bitnami/apache:2.4.34
docker run -d -p 8083:80 bitnami/apache:latest
```

The first link works (as expected, mapping port 80) the second and third links fail:

- http://localhost:8081
- http://localhost:8082
- http://localhost:8083

3. [Check exposed ports]

```
$ docker inspect --format='{{.ContainerConfig.ExposedPorts}}' bitnami/apache:2.4.33
map[443/tcp:{} 80/tcp:{}]

$ docker inspect --format='{{.ContainerConfig.ExposedPorts}}' bitnami/apache:2.4.34
map[8080/tcp:{} 8443/tcp:{}]

$ docker inspect --format='{{.ContainerConfig.ExposedPorts}}' bitnami/apache:latest
map[8080/tcp:{} 8443/tcp:{}]
```

**Describe the results you received:**

I did not expect the exposed ports to change in the latest image. This caused my Kubenetes deployment to fail. Obviously having a build dependency on the latest image is a bad idea, this was a Development build. 

**Describe the results you expected:**

Is this an planned change? Confusingly the Dockerfile in Dockerhub shows ports 80 + 443 exposed:

https://hub.docker.com/r/bitnami/apache/~/dockerfile/

Same in github, where the Dockerfile appears to be building 2.4.34:

https://github.com/bitnami/bitnami-docker-apache/blob/master/2.4/Dockerfile

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:38 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:45 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
$ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 56
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 277
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-29-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.26GiB
Name: mark-XPS-15-9560
ID: DKSZ:THDG:V6I2:32JA:2DQR:U23B:NERW:5S4G:A7Z5:KPAM:CYZQ:LHKV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: myspotontheweb
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi,

You are seeing these changes because the Bitnami Apache container now runs as a non-root user, since version 2.4.34-r8 of the container. This way, it now supports OpenShift containers.

However, it seems that we did not update the README, as it's still referring to port 80/443 (not 8080:8443) and the non-root changes are not mentioned in [Notable Changes](https://github.com/bitnami/bitnami-docker-apache#notable-changes). We will work on fixing this ASAP.

Sorry for the inconvenience.

**Comment by myspotontheweb** [comment]
Makes perfect sense. Thanks for the update!

**Comment by marcosbc** [comment]
Hi @myspotontheweb, we wanted to let you know that we added a line in the [Notable Changes](https://github.com/bitnami/bitnami-docker-apache#2434-r8) section in the README, with the explanation.
