### ISSUE TITLE
setup for url rewriting, permission for running in rancher

### ISSUE THREAD

**Issue by MirKml** [bitnami/bitnami-docker-apache#91]
Hello, can you help me with simple setup for the url rewriting?
I tried to setup your docker image, main application is copied into /app folder and it works. Then I tried to setup url rewriting via .htaccess. I run the container with volume for .htaccess file:

    docker run --name mywebapp -p 8080:8080 -v ${HOME}/bitnami-docker/htaccess:/app/.htaccess derived-bitnami-apache.

It's fine but simple rewrite for testing doesn't work. Content of ${HOME}/bitnami-docker/htaccess

    RewriteEngine on
    RewriteBase /
    RewriteRule "/tesUrl"  "http://www.example.com"  [R]

But it doesn't work. There is no such redirects. Log entry for such request is 

    192.168.56.1 - - [29/Nov/2018:23:46:02 +0000] "GET /testUrl HTTP/1.1" 404 205
    192.168.56.1 - - [29/Nov/2018:23:46:53 +0000] "-" 408 -

Sorry for such basic question. But I tried it many times, also via mounted virtual host configuration, but nothing works.

**Comment by MirKml** [comment]
fixed with particular configuration for virtual host in my_virthost.conf, which is later used as volume for the virtual host configuration. Rewrites inside it work fine. Can close issue.

```
<VirtualHost _default_:8080>
  DocumentRoot "/opt/bitnami/apache/htdocs"

  RewriteEngine On
  RewriteRule ^/$ /about/ [R,L]
  RewriteRule ....
</VirtualHost>
```

**Comment by MirKml** [comment]
Yes, for redirects, I can use mod_redirect directives, but for "inner" redirects for e.g. application startup - index.php -  I need mod_rewrite, it works only with my workaround.

**Comment by andresbono** [comment]
Hi @MirKml, thanks for sharing the way you have solved your redirection issue. We are going to close it.
