### ISSUE TITLE
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/apache/conf/vhosts/htaccess'

### ISSUE THREAD

**Issue by dcorral** [bitnami/bitnami-docker-apache#92]
Hi,

I tried to [add a custom virtual host configuration](https://github.com/bitnami/bitnami-docker-apache#adding-custom-virtual-hosts) but the following command failed:

```bash
$ docker run --name apache \
  -v $PWD/my_vhost.conf:/bitnami/apache/conf/vhosts/my_vhost.conf:ro \
  bitnami/apache:latest
```

with this message:

```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/apache/conf/vhosts/htaccess'
```

Before the [2.4.34-r8](https://github.com/bitnami/bitnami-docker-apache#2434-r8) (non-root container), it works perfectly but since all later versions don't work.

To fix this issue, I added `/opt/bitnami/apache/conf` to the variable `BITNAMI_PKG_EXTRA_DIRS` in the Dockerfile:
```Dockerfile
ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
    BITNAMI_PKG_EXTRA_DIRS="/bitnami/apache/conf /opt/bitnami/apache/conf /opt/bitnami/apache/tmp /bitnami/apache/conf/vhosts" \
    HOME="/"
```

Now it works:

```bash
$ docker build -t dcorral/apache .
$ docker run --name apache \
  -v $PWD/my_vhost.conf:/bitnami/apache/conf/vhosts/my_vhost.conf:ro \
  dcorral/apache:latest
```

give me:

```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
INFO  ==> Starting apache...
INFO  ==> Starting httpd...
```

I hope it could be useful!

**Comment by dcorral** [comment]
With modified image (BITNAMI_PKG_EXTRA_DIRS):
```
$ docker run --rm -v $PWD/my_vhost.conf:/bitnami/apache/conf/vhosts/my_vhost.conf:ro dcorral/apache ls -l /bitnami/apache/conf

Welcome to the Bitnami apache container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-apache
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-apache/issues

total 4
drwxrwxr-x 1 root root 4096 Mar  6 05:35 vhosts
```

Original image

```
$ docker run --rm -v $PWD/my_vhost.conf:/bitnami/apache/conf/vhosts/my_vhost.conf:ro bitnami/apache ls -l /bitnami/apache/conf

Welcome to the Bitnami apache container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-apache
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-apache/issues

total 4
drwxr-xr-x 2 root root 4096 Mar  6 05:33 vhosts
```

**Comment by marcosbc** [comment]
Hi @dcorral, thanks for sharing this. We are aware of this specific issue and are evaluating different approaches for improving UX when mounting configuration files.

We'll update this issue once we start working on the changes.

**Comment by jakelacey2012** [comment]
I'm also getting this issue, adding those environment variables don't fix it for me. Is there a version I can use which works and is recent?

**Comment by juan131** [comment]
Hi @jakelacey2012 

Could you share the command you're using to run the Apache container? 
Could you please also provide the Dockerfile you used to add the corresponding environment variables?

**Comment by jakelacey2012** [comment]
Sure @juan131 

So i'm using docker-compose with a configuration that follows this.
```yml
version: '3'

services:

  # https://github.com/bitnami/bitnami-docker-apache/issues/92
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '443:443'
    volumes:
      - ./my_vhost.conf:/bitnami/apache/conf/vhosts/my_vhost.conf
```

I've tried setting the environment variables,
```yml
env:
    BITNAMI_PKG_CHMOD="-R g+rwX
    BITNAMI_PKG_EXTRA_DIRS="/bitnami/apache/conf /opt/bitnami/apache/conf /opt/bitnami/apache/tmp /bitnami/apache/conf/vhosts" 
```

Let me know what I could be missing :)

**Comment by jakelacey2012** [comment]
Okay if after I update docker to the latest version I get a different error
```
apache_1      | Error executing 'postInstallation': Module mod_version is not present in the configuration file, you need to provide a module ident
ifier in the options parameter along with the module n
```

**Comment by juan131** [comment]
> I've tried setting the environment variables,
> 
> env:
>     BITNAMI_PKG_CHMOD="-R g+rwX
 >    BITNAMI_PKG_EXTRA_DIRS="/bitnami/apache/conf /opt/bitnami/apache/conf /opt/bitnami/apache/tmp /bitnami/apache/conf/vhosts"
> Let me know what I could be missing :)

That env. variable modifies the permissions when the command **bitnami-pkg** is run:

https://github.com/bitnami/bitnami-docker-apache/blob/master/2.4/debian-9/Dockerfile#L10

Therefore, if you modify the environment in the **docker-compose.yml**, it son't work. You need to do it in the Dockerfile and rebuild the image.

You can check the **bitnami-pkg** code by running the command below:

```bash
$ docker run --rm bitnami/apache cat /usr/local/bin/bitnami-pkg
```

**Comment by alemorcuq** [comment]
Hi, @dcorral, @jakelacey2012.

We recently moved all the logic of this container to Bash, and you can find it under the `rootfs` folder in this repository. Custom virtual hosts should be mounted to the `/vhosts` directory [as specified in the documentation](https://github.com/bitnami/bitnami-docker-apache#adding-custom-virtual-hosts):

Using `docker run`:

```bash
$ docker run --name apache \
  -v /path/to/my_vhost.conf:/vhosts/my_vhost.conf:ro \
  bitnami/apache:latest
```

Using `docker-compose`:

```yaml
version: '2'

services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /path/to/my_vhost.conf:/vhosts/my_vhost.conf:ro
```

Regards,
Alejandro
