### ISSUE TITLE
How to extend Dockerfile to prebuild own theme

### ISSUE THREAD

**Issue by tpoxa** [bitnami/bitnami-docker-apache#97]
I do next:
```

FROM docker.io/bitnami/wordpress:latest
ADD theme /bitnami/wordpress/wp-content/themes
```
But my theme does not appear in container's wp-content after helm installation. Is there any folder where I can mount own theme?

**Comment by rafariossaa** [comment]
Hi,
  You should use the `/opt/bitnami/wodpress/wp-content/themes`, the content from here is copied to `/bitnami/...` and them symlinked. 
  Also you could use a local volume mounted mounted in `/bitnami/wordpress`.

**Comment by tpoxa** [comment]
Thank you.
