### ISSUE TITLE
Cant forward HTTP to HTTPS

### ISSUE THREAD

**Issue by TinNguyen331** [bitnami/bitnami-docker-apache#98]
Hello, i try to config my own SSL certificate and it work good on 443 port.But have error when i try connect in port 80. I don't know how to config Apache forward http port 80 to https port 443 vhost but seem not working.
Have any idea.?

Thank you so much

**Comment by Mauraza** [comment]
Hello @TinNguyen331 
Have you tried this [https://github.com/bitnami/bitnami-docker-apache#adding-custom-virtual-hosts](https://github.com/bitnami/bitnami-docker-apache#adding-custom-virtual-hosts )?
